grafana:
  adminPassword: "admin"
  service:
    type: ClusterIP
  ingress:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true