apiVersion: apps/v1
kind: Deployment
metadata:
  name: emmanuel-services
  labels:
    app: emmanuel-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emmanuel-services
  template:
    metadata:
      labels:
        app: emmanuel-services
    spec:
      containers:
      - name: emmanuel-services
        image: 780593603882.dkr.ecr.us-east-1.amazonaws.com/emmanuel-services:latest  # e.g. 123456789.dkr.ecr.us-east-1.amazonaws.com/emmanuel-services:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
